if(EXISTS "/mnt/c/Users/germa/Documents/4d engine/build-linux/tests/hopf_tests-b12d07c_tests.cmake")
  include("/mnt/c/Users/germa/Documents/4d engine/build-linux/tests/hopf_tests-b12d07c_tests.cmake")
else()
  add_test(hopf_tests_NOT_BUILT-b12d07c hopf_tests_NOT_BUILT-b12d07c)
endif()
